/*
======================SALES PERFORMANCE=====================

1 - TOP PRODUCTS/CATEGORIES
    A) NETWORK & LOCATION
    B) TOP 80% OF PRODUCTS
      B1) QUANTITY/TOTAL REV
    C) TOP DRIVERS (TOTAL ORDERS)
2 - SEASONALITY
    A) BY MFC & CATEGORY (WEEK)
    B) HOURLY (ALL PRODUCT)
=============================================================
*/
SELECT DISTINCT FORMAT_TIMESTAMP('%F %T', TIMESTAMP(DATETIME(DELIV_CREATED_AT), 'America/New_York')) AS EST_TS
  ,DATE(TIMESTAMP(DATETIME(DELIV_CREATED_AT), 'America/New_York')) AS EST_DT
  ,EXTRACT(HOUR FROM TIMESTAMP(DATETIME(DELIV_CREATED_AT), 'America/New_York')) AS HR
  ,EXTRACT(MINUTE FROM TIMESTAMP(DATETIME(DELIV_CREATED_AT), 'America/New_York')) AS MINUTE
  ,DELIV_STORE_NAME AS STORE
  ,DELIV_DASHER_ID AS DASHER_ID
  ,DELIV_D2R AS D2R
  ,DELIV_IS_20_MIN_LATE AS LATE_FLG
  ,DELIV_CLAT
  ,CAST(DELIV_MISSING_INCORRECT_REPORT AS INT64) AS COMPLAINT
  ,WAS_REQUESTED
  ,WAS_MISSING
  ,WAS_SUBBED
  ,WAS_FOUND
  ,ITEM_CATEGORY
  ,ITEM_NAME
  ,SUBSTITUTE_ITEM_CATEGORY AS SUB_CAT
  ,SUBSTITUTE_ITEM_NAME AS SUB_ITEM
  ,MAX(ITEM_PRICE) AS ITEM_PRICE
FROM `couch2coding.DoorDash_Case_Study.NEW_VERTICALS` 
GROUP BY ALL
-- GROUP BY ALL
-- HAVING T > 1
-- SELECT DISTINCT DELIV_STORE_NAME
-- SELECT DELIV_STORE_NAME
--   ,COUNT(DISTINCT DELIVERY_UUID) AS N_DLVS
--   ,COUNT(DISTINCT DELIV_DASHER_ID) AS N_DASHERS
--   ,AVG(DELIV_D2R) AS AVG_D2R
--   ,AVG(DELIV_IS_20_MIN_LATE) AS AVG_LATE
-- SELECT DISTINCT *
-- FROM `couch2coding.DoorDash_Case_Study.NEW_VERTICALS` 
-- WHERE DELIVERY_UUID = 'e1e40ffa-1ca6-48f9-b764-339a1aab863d'
-- AND ITEM_NAME = "Favorite Day Brownie Bites"

